/**
 * Emits supabase/seed.sql from the @jyotir/content bundles.
 *
 *   pnpm seed:generate
 *   supabase db reset   (or: psql $DATABASE_URL -f supabase/seed.sql)
 *
 * Upserts are idempotent on the stable text ids, so re-running after a
 * content edit updates rows in place. study_materials.total_linked_questions
 * is intentionally not written — the DB trigger maintains it as questions
 * are inserted.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { exams, subjects, topics, materials, questions } from "@jyotir/content";

const q = (v: string | number): string =>
  typeof v === "number" ? String(v) : `'${v.replace(/'/g, "''")}'`;

const upsert = (
  table: string,
  columns: string[],
  rows: (string | number)[][],
  updateCols: string[]
): string => {
  const values = rows.map((r) => `  (${r.map(q).join(", ")})`).join(",\n");
  const updates = updateCols.map((c) => `${c} = excluded.${c}`).join(", ");
  return `insert into public.${table} (${columns.join(", ")})\nvalues\n${values}\non conflict (id) do update set ${updates};\n`;
};

const sql = [
  "-- Generated by scripts/generate-seed.ts — do not edit by hand.",
  `-- Source: @jyotir/content (${exams.length} exams, ${topics.length} topics, ${materials.length} micro-notes, ${questions.length} questions)`,
  "begin;",
  upsert(
    "exams",
    ["id", "name", "slug", "tagline", "order_index"],
    exams.map((e) => [e.id, e.name, e.slug, e.tagline, e.orderIndex]),
    ["name", "slug", "tagline", "order_index"]
  ),
  upsert(
    "subjects",
    ["id", "exam_id", "name", "slug", "order_index"],
    subjects.map((s) => [s.id, s.examId, s.name, s.slug, s.orderIndex]),
    ["exam_id", "name", "slug", "order_index"]
  ),
  upsert(
    "topics",
    ["id", "subject_id", "name", "slug", "order_index"],
    topics.map((t) => [t.id, t.subjectId, t.name, t.slug, t.orderIndex]),
    ["subject_id", "name", "slug", "order_index"]
  ),
  upsert(
    "study_materials",
    ["id", "topic_id", "title", "content", "estimated_read_time", "order_index"],
    materials.map((m) => [m.id, m.topicId, m.title, m.content, m.estimatedReadTime, m.orderIndex]),
    ["topic_id", "title", "content", "estimated_read_time", "order_index"]
  ),
  upsert(
    "questions",
    ["id", "topic_id", "text", "option_a", "option_b", "option_c", "option_d", "correct_option", "explanation", "order_index"],
    questions.map((x) => [
      x.id, x.topicId, x.text, x.optionA, x.optionB, x.optionC, x.optionD, x.correctOption, x.explanation, x.orderIndex
    ]),
    ["topic_id", "text", "option_a", "option_b", "option_c", "option_d", "correct_option", "explanation", "order_index"]
  ),
  "commit;",
  ""
].join("\n\n");

const out = join(dirname(fileURLToPath(import.meta.url)), "..", "supabase", "seed.sql");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, sql);
console.log(
  `wrote ${out}: ${exams.length} exams, ${subjects.length} subjects, ${topics.length} topics, ${materials.length} materials, ${questions.length} questions`
);
